name: realworld-armeria-local-env

services:
  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: realworld
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql
